const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
const {installSupabaseMock,database}=require('./supabase-mock.cjs');
const URL=process.env.VIEWER_URL||'http://127.0.0.1:8788/';
const wait=async(fn,message)=>{const end=Date.now()+20000;while(!fn()){if(Date.now()>end)throw new Error(message);await new Promise(r=>setTimeout(r,60));}};
const ready=async(page,id)=>page.waitForFunction(id=>window.__homeViewer?.snapshot().schemeId===id&&!document.querySelector('.loading'),id,{timeout:120000});
const snapshot=page=>page.evaluate(()=>window.__homeViewer.snapshot());
const change=async(page,id)=>{await page.getByLabel('切换家装方案').selectOption(id);await ready(page,id);};
const setX=async(page,value)=>{
 await page.getByRole('button',{name:'自由查看',exact:true}).click();
 await page.getByRole('button',{name:'选中物件',exact:true}).click();
 await page.locator('.object-list button').filter({hasText:'白色布艺沙发'}).first().click();
 await page.getByLabel('家具横向位置').fill(String(value));await page.getByLabel('家具横向位置').press('Tab');
};
const create=async(page,name,source='copy')=>{
 await page.getByRole('button',{name:'＋ 新建方案',exact:true}).click();
 await page.getByLabel('方案名称', {exact:true}).fill(name);await page.getByLabel('起始布置').selectOption(source);
 await page.getByRole('button',{name:'创建方案',exact:true}).click();
 await page.waitForFunction(()=>!document.querySelector('.loading')&&!document.querySelector('.scheme-dialog[open]'),{},{timeout:120000});
 return (await snapshot(page)).schemeId;
};
(async()=>{
 fs.mkdirSync('test-results',{recursive:true});
 const browser=await chromium.launch({channel:'msedge',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
 try{
  const db=database(),context=await browser.newContext({viewport:{width:1536,height:1000}});
  await installSupabaseMock(context,{signedIn:false,db});
  const page=await context.newPage(),errors=[],checks=[];const check=message=>{checks.push(message);console.log('PASS: '+message);};page.on('pageerror',e=>errors.push(e.message));
  console.log('Starting cloud browser checks');await page.goto(URL);await ready(page,'original');
  assert(await page.getByRole('button',{name:'＋ 新建方案',exact:true}).isDisabled());
  assert(await page.locator('.catalog-card').first().isDisabled());
  await page.getByRole('button',{name:'清水房',exact:true}).click();assert.equal(db.writes.length,0);
  check('Guest browsing never uploads changes and disables editing/creation');
  await page.getByRole('button',{name:'登录编辑',exact:true}).first().click();
  await page.getByLabel('登录邮箱').fill('editor@example.test');await page.getByLabel('登录密码').fill('test-password');
  await page.getByRole('button',{name:'登录',exact:true}).click();
  await page.getByRole('button',{name:'退出',exact:true}).waitFor();await ready(page,'original');
  await wait(()=>db.rows.has('original'),'Login did not initialize the cloud design');
  const sofa=(await snapshot(page)).entities.find(e=>e.name==='白色布艺沙发'),id=sofa.id;
  await setX(page,1.1);await wait(()=>db.rows.get('original')?.layout.entities.find(e=>e.id===id).position[0]===1.1,'Furniture edit not saved');
  await page.getByRole('button',{name:'隐藏次卧装修',exact:true}).click();
  await wait(()=>db.rows.get('original')?.layout.rooms['guest']?.decorated===false||Object.values(db.rows.get('original').layout.rooms).some(r=>!r.decorated),'Room edit not saved');
  check('Email/password login enables furniture and room autosave');
  db.delay=1000;const count=db.writes.length;
  await setX(page,1.2);await wait(()=>db.writes.length>count,'First save did not start');
  await setX(page,1.3);await setX(page,1.4);
  await wait(()=>db.rows.get('original').layout.entities.find(e=>e.id===id).position[0]===1.4,'In-flight save lost a newer edit');
  db.delay=0;await page.locator('.cloud-status[data-state=saved]').waitFor();
  const original=structuredClone(db.rows.get('original').layout),revision=db.rows.get('original').revision;
  await page.reload();await ready(page,'original');await new Promise(r=>setTimeout(r,800));
  assert.equal(db.rows.get('original').revision,revision,'Reading an unchanged layout caused a write');
  check('Rapid edits drain in order; reloading unchanged JSON does not resave');
  const copyId=await create(page,'暖木客厅 · 副本');await wait(()=>db.rows.has(copyId),'New copy did not save');
  assert.deepEqual(db.rows.get(copyId).layout,original);assert.deepEqual(db.rows.get('original').layout,original);
  await setX(page,2.2);await wait(()=>db.rows.get(copyId).layout.entities.find(e=>e.id===id).position[0]===2.2,'Copy edit did not save');
  assert.deepEqual(db.rows.get('original').layout,original);
  const templateId=await create(page,'新户型初始方案','alternative');await wait(()=>db.rows.has(templateId),'Template design did not save');
  assert.equal(db.rows.get(templateId).template_id,'alternative');assert.equal(db.rows.get(templateId).layout.modelVersion,'2026-09-14-plan-b');
  check('Copy and initial-template creation persist distinct designs with the correct model');
  await change(page,copyId);db.offline=true;await setX(page,2.5);
  await page.locator('.cloud-status[data-state=error]').waitFor();
  await page.reload();await ready(page,copyId);
  assert.equal((await snapshot(page)).entities.find(e=>e.id===id).position[0],2.5);
  db.offline=false;await page.evaluate(()=>window.dispatchEvent(new Event('online')));
  await wait(()=>db.rows.get(copyId).layout.entities.find(e=>e.id===id).position[0]===2.5,'Offline outbox did not resume');
  await page.locator('.cloud-status[data-state=saved]').waitFor();
  check('Offline edits survive refresh and resume on reconnection');
  const beforeRetry=db.rows.get(copyId).revision;db.loseResponse=true;await setX(page,2.6);
  await page.locator('.cloud-status[data-state=error]').waitFor();await page.getByRole('button',{name:'重试保存',exact:true}).click();
  await page.locator('.cloud-status[data-state=saved]').waitFor();assert.equal(db.rows.get(copyId).revision,beforeRetry+1);
  check('Retry after a lost response does not apply the same write twice');
  const otherContext=await browser.newContext({viewport:{width:1536,height:1000}});await installSupabaseMock(otherContext,{db});
  const other=await otherContext.newPage();other.on('pageerror',e=>errors.push(e.message));await other.goto(URL);await ready(other,'original');
  await change(page,'original');await setX(page,3.1);await wait(()=>db.rows.get('original').layout.entities.find(e=>e.id===id).position[0]===3.1,'First editor did not save');
  await setX(other,3.2);await other.locator('.cloud-status[data-state=conflict]').waitFor();
  assert.equal(db.rows.get('original').layout.entities.find(e=>e.id===id).position[0],3.1);
  await other.getByRole('button',{name:'另存本地副本',exact:true}).click();
  await other.waitForFunction(()=>window.__homeViewer?.snapshot().schemeId!=='original'&&!document.querySelector('.loading'),{},{timeout:120000});
  const conflictId=(await snapshot(other)).schemeId;await wait(()=>db.rows.has(conflictId),'Conflict copy did not save');
  assert.equal(db.rows.get(conflictId).layout.entities.find(e=>e.id===id).position[0],3.2);
  check('Two editors cannot silently overwrite each other; conflict can become a new design');
  await page.screenshot({path:'test-results/cloud-desktop.png'});
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/cloud-mobile.png'});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.getByRole('button',{name:'＋ 新建方案',exact:true}).click();await page.screenshot({path:'test-results/cloud-new-design-mobile.png'});
  await page.keyboard.press('Escape');assert.equal(await page.locator('dialog[open]').count(),0);
  await page.getByRole('button',{name:'退出',exact:true}).click();await ready(page,'original');
  assert(await page.getByRole('button',{name:'＋ 新建方案',exact:true}).isDisabled());
  check('Mobile controls fit the viewport; dialogs close with Escape; logout restores read-only');
  const guestContext=await browser.newContext({viewport:{width:1280,height:900}});await installSupabaseMock(guestContext,{signedIn:false,db});
  const guest=await guestContext.newPage();await guest.goto(URL);await ready(guest,'original');await change(guest,copyId);
  assert.equal((await snapshot(guest)).entities.find(e=>e.id===id).position[0],2.6);
  assert(await guest.locator('.catalog-card').first().isDisabled());
  check('A fresh unauthenticated browser can read shared cloud plans');
  assert.deepEqual(errors,[]);fs.writeFileSync('test-results/cloud-report.json',JSON.stringify({passed:true,checks},null,2));console.log(JSON.stringify({passed:true,checks},null,2));
 }catch(error){for(const [i,p] of browser.contexts().flatMap(c=>c.pages()).entries()){console.error('Page '+i+': '+await p.locator('body').innerText().catch(()=>''));await p.screenshot({path:'test-results/cloud-failure-'+i+'.png'}).catch(()=>{});}throw error;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
