const {chromium}=require('playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
 const page=await browser.newPage({viewport:{width:1536,height:1000}}),errors=[],checks=[];
 page.on('pageerror',e=>errors.push(e.message));
 const snap=()=>page.evaluate(()=>window.__homeViewer.snapshot());
 const ready=async()=>{await page.waitForFunction(()=>window.__homeViewer&&document.querySelector('.loading')===null);await page.waitForTimeout(700);};
 const lock=()=>page.getByRole('button',{name:'锁定物件',exact:true});
 const layout=s=>s.entities.map(e=>[e.id,e.position,e.rotation,e.scale,e.deleted]);
 await page.goto(process.env.VIEWER_URL||'http://127.0.0.1:8788/');await ready();assert.equal(await lock().getAttribute('aria-pressed'),'false');
 const a=await lock().boundingBox(),wall=await page.getByLabel('自动隐藏最近墙面').locator('..').boundingBox();assert(a.x+a.width<=wall.x&&Math.abs(a.y-wall.y)<15);
 checks.push('Unlocked by default; lock button appears immediately left of wall hiding');
 await page.getByRole('button',{name:'查看客厅',exact:true}).click();await page.waitForTimeout(800);
 await page.getByRole('button',{name:'添加蛋黄旋转单椅',exact:true}).click();await page.waitForTimeout(250);
 let s=await snap();const id=s.selection;assert(id);const original=layout(s),history=s.history;
 await lock().click();await page.waitForTimeout(150);assert.equal((await snap()).selection,null);assert.equal(await lock().getAttribute('aria-pressed'),'true');
 assert(await page.locator('.object-list button').first().isDisabled());assert.equal(await page.getByLabel('家具横向位置').count(),0);
 const en=(await snap()).entities.find(e=>e.id===id);await page.mouse.click(...en.screen);assert.equal((await snap()).selection,null);
 const camera=(await snap()).camera;await page.mouse.move(...en.screen);await page.mouse.down();await page.mouse.move(en.screen[0]+80,en.screen[1]+30,{steps:12});await page.mouse.up();await page.waitForTimeout(500);
 s=await snap();assert.deepEqual(layout(s),original);assert.deepEqual(s.history,history);assert.equal(s.selection,null);assert(Math.hypot(...s.camera.map((v,i)=>v-camera[i]))>.05);
 await page.keyboard.press('Delete');assert.deepEqual(layout(await snap()),original);
 checks.push('Lock clears selection, blocks canvas picking/dragging and list picking while orbit remains usable');
 await page.getByRole('button',{name:'家具样式库',exact:true}).click();assert(await page.getByRole('button',{name:'添加蛋黄旋转单椅',exact:true}).isDisabled());
 await page.getByRole('button',{name:'重置视角',exact:false}).click();await page.waitForTimeout(800);await page.screenshot({path:'test-results/object-lock.png'});
 await lock().click();await page.getByRole('button',{name:'选中物件',exact:true}).click();await page.locator('.object-list button').filter({hasText:'蛋黄旋转单椅'}).last().click();await page.waitForTimeout(800);assert.equal((await snap()).selection,id);
 const before=(await snap()).entities.find(e=>e.id===id);await page.mouse.move(...before.screen);await page.mouse.down();await page.mouse.move(before.screen[0]+70,before.screen[1]+30,{steps:10});await page.mouse.up();await page.waitForTimeout(200);
 const moved=(await snap()).entities.find(e=>e.id===id);assert(Math.hypot(...moved.position.map((v,i)=>v-before.position[i]))>.1);
 checks.push('Unlock restores selection and direct furniture dragging');
 await lock().click();await page.getByLabel('切换家装方案').selectOption('alternative');await ready();assert.equal(await lock().getAttribute('aria-pressed'),'true');
 await page.getByRole('button',{name:'选中物件',exact:true}).click();assert(await page.locator('.object-list button').first().isDisabled());assert.equal((await snap()).selection,null);
 await lock().click();await page.locator('.object-list button').filter({hasText:'白色布艺沙发'}).first().click();await page.waitForTimeout(250);assert((await snap()).selection);
 await lock().click();await page.reload();await ready();assert.equal(await lock().getAttribute('aria-pressed'),'false');
 checks.push('Both schemes honor the session lock; page reload defaults to unlocked');
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(500);assert(await lock().isVisible());assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await lock().click();await page.waitForFunction(()=>document.querySelector('.object-lock')?.getAttribute('aria-pressed')==='true');await page.screenshot({path:'test-results/object-lock-mobile.png'});
 checks.push('Mobile lock control remains visible and usable');
 assert.deepEqual(errors,[]);fs.writeFileSync('test-results/object-lock-report.json',JSON.stringify({passed:true,checks,consoleErrors:errors},null,2));console.log(JSON.stringify({passed:true,checks:checks.length}));await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
