const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
const {installSupabaseMock,database}=require('./supabase-mock.cjs');
const BASE=process.env.VIEWER_URL||'http://127.0.0.1:8788/';
const legacyKey='home-simulator:raw-workspace:v1';
const cache='home-simulator:supabase:nbdodqezyijrztikvkcd:v1:';
const seed=JSON.parse(fs.readFileSync('test-results/raw-shell-layout.json','utf8'));
const legacy=[{id:'raw-shell',name:'我的原户型',layout:seed},{id:'local-existing',name:'已改墙体的布置',layout:seed}];
const ready=(p,id)=>p.waitForFunction(id=>window.__homeViewer?.snapshot().schemeId===id&&!document.querySelector('.loading'),id,{timeout:120000});
const snap=p=>p.evaluate(()=>window.__homeViewer.snapshot());
const change=async(p,id)=>{await require('./scheme-ui.cjs').selectScheme(p,id);await ready(p,id);};
const wait=async f=>{const end=Date.now()+20000;while(!f()){if(Date.now()>end)throw new Error('Timed out waiting for save');await new Promise(r=>setTimeout(r,60));}};
const exportLayout=async p=>{const event=p.waitForEvent('download');await p.getByRole('button',{name:'导出方案',exact:true}).click();return JSON.parse(fs.readFileSync(await(await event).path(),'utf8'));};
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
 const errors=[],checks=[];const db=database();
 try{
  const context=await browser.newContext({viewport:{width:1536,height:1000},acceptDownloads:true});
  await installSupabaseMock(context,{signedIn:false,db});
  await context.addInitScript(({legacy,key})=>{
   if(!localStorage.getItem('unified-test-seed')){
    localStorage.setItem(key,JSON.stringify(legacy));localStorage.setItem('home-simulator:active-raw-design','local-existing');
    for(const d of legacy)localStorage.setItem(d.id==='raw-shell'?'home-simulator:raw-shell:2026-09-15:v1':'home-simulator:design:'+d.id,JSON.stringify(d.layout));
    localStorage.setItem('unified-test-seed','1');
   }
  },{legacy,key:legacyKey});
  const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
  await page.goto(BASE+'?workspace=raw');await ready(page,'local-existing');
  assert(!new URL(page.url()).searchParams.has('workspace'));assert.equal(new URL(page.url()).searchParams.get('scheme'),'local-existing');
  assert.equal(await page.getByRole('link',{name:/云端方案|清水房工作台/}).count(),0);
  assert.equal(await page.getByRole('listbox',{name:'切换家装方案'}).getByRole('option').count(),4);
  assert.equal(await page.locator('.topbar select').count(),0);
  assert(await page.evaluate(()=>document.querySelector('.scheme-explorer').getBoundingClientRect().bottom<=document.querySelector('.list-heading').getBoundingClientRect().top));
  assert.equal((await page.locator('.topbar').boundingBox()).height,48);
  await page.locator('.scheme-file[aria-selected=true]').focus();await page.keyboard.press('Home');
  assert.equal(await page.locator('.scheme-file:focus').getAttribute('data-scheme-id'),'original');
  await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');await ready(page,'alternative');
  await change(page,'local-existing');
  await page.locator('.scheme-section-toggle').click();await page.locator('#scheme-files').waitFor({state:'hidden'});
  await page.locator('.scheme-section-toggle').click();await page.locator('#scheme-files').waitFor({state:'visible'});
  checks.push('Compact header, sidebar file selection above rooms, keyboard navigation and collapsible scheme section');
  assert.deepEqual((await exportLayout(page)).walls,seed.walls);assert.deepEqual((await exportLayout(page)).entities,seed.entities);
  assert.equal(db.writes.length,0);
  checks.push('Old raw URL opens unified app; legacy designs, wall edits, furniture and current selection migrate without uploading');
  let navigations=0;page.on('request',request=>{if(request.isNavigationRequest()&&request.resourceType()==='document')navigations++;});
  await change(page,'original');assert.equal((await snap(page)).modelVersion,'2026-09-14');
  assert(await page.getByRole('button',{name:'新建方案',exact:true}).isDisabled());
  await change(page,'alternative');assert.equal((await snap(page)).modelVersion,'2026-09-14-plan-b');
  await change(page,'local-existing');assert.equal((await snap(page)).modelVersion,'2026-09-15-raw-shell');
  assert.equal(navigations,0,'Changing floor plans navigated to a different workbench');
  await page.getByRole('button',{name:'家具库',exact:true}).click();await page.getByRole('button',{name:'添加蛋黄旋转单椅',exact:true}).click();
  const edited=await exportLayout(page);assert.equal(edited.entities.length,seed.entities.length+1);
  await page.goto(BASE);await ready(page,'local-existing');assert.deepEqual((await exportLayout(page)).entities,edited.entities);
  assert.equal(await page.getByRole('listbox',{name:'切换家装方案'}).getByRole('option').count(),4);
  assert.deepEqual(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)),legacyKey),legacy);
  checks.push('All three templates switch without page navigation; root URL remembers the same active design; old archive stays intact and migration is idempotent');
  await page.getByRole('button',{name:'新建方案',exact:true}).click();
  assert.deepEqual(await page.getByLabel('起始布置').locator('option').evaluateAll(nodes=>nodes.map(n=>n.value)),['copy','original','alternative','raw-shell']);
  await page.getByLabel('方案名称',{exact:true}).fill('统一入口新建方案二');await page.getByLabel('起始布置').selectOption('alternative');
  await page.getByRole('button',{name:'创建方案',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('.loading')&&!document.querySelector('.scheme-dialog[open]'));
  const made=(await snap(page)).schemeId;assert(made.startsWith('local-'));assert.equal((await snap(page)).modelVersion,'2026-09-14-plan-b');
  assert.equal(await page.locator('.scheme-file[aria-selected=true]').getAttribute('data-scheme-id'),made,'File list must highlight the newly created design');
  await page.getByRole('button',{name:'家具库',exact:true}).click();await page.getByRole('button',{name:'添加蛋黄旋转单椅',exact:true}).click();
  const madeLayout=await exportLayout(page);await change(page,'local-existing');assert.deepEqual((await exportLayout(page)).entities,edited.entities);
  await change(page,made);assert.deepEqual((await exportLayout(page)).entities,madeLayout.entities);
  checks.push('One new-design dialog supports every template; cross-template local designs retain independent furniture and edits');
  await change(page,'local-existing');
  await page.getByRole('button',{name:'登录编辑',exact:true}).first().click();
  await page.getByLabel('登录邮箱').fill('editor@example.test');await page.getByLabel('登录密码').fill('test-password');await page.getByRole('button',{name:'登录',exact:true}).click();
  await page.getByRole('button',{name:'保存到云端',exact:true}).waitFor();await ready(page,'local-existing');assert.equal(db.writes.length,0,'Login unexpectedly published private designs');
  await page.getByRole('button',{name:'保存到云端',exact:true}).click();
  await page.waitForFunction(()=>window.__homeViewer?.snapshot().schemeId!=='local-existing'&&!document.querySelector('.loading'));
  const shared=(await snap(page)).schemeId;await wait(()=>db.rows.has(shared));
  assert.equal(db.rows.get(shared).template_id,'raw-shell');assert.deepEqual(db.rows.get(shared).layout,edited);
  await change(page,'local-existing');assert.deepEqual(await exportLayout(page),edited);
  const otherContext=await browser.newContext({viewport:{width:1400,height:1000}});await installSupabaseMock(otherContext,{signedIn:false,db});
  const other=await otherContext.newPage();other.on('pageerror',e=>errors.push(e.message));await other.goto(BASE+'?scheme='+shared);await ready(other,shared);
  assert.deepEqual(JSON.parse(JSON.stringify((await snap(other)).architecture.walls)),edited.walls);assert(await other.locator('.catalog-card').first().isDisabled());
  checks.push('Explicit sharing sends full raw model layout through the same cloud store, keeps private source, and is readable from a fresh browser with existing permissions');
  db.rejectRaw=true;await page.getByRole('button',{name:'保存到云端',exact:true}).click();
  await page.locator('.cloud-status[data-state=error]').waitFor();assert.match(await page.locator('.cloud-status').innerText(),/需更新户型支持/);
  const pending=(await snap(page)).schemeId;assert(!db.rows.has(pending));
  const outbox=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)),cache+pending);assert(outbox.dirty);assert.deepEqual(outbox.row.layout,edited);
  db.rejectRaw=false;await page.getByRole('button',{name:'重试保存',exact:true}).click();await wait(()=>db.rows.has(pending));
  checks.push('Older database rejects unsupported template clearly; durable layout remains pending and retries after server upgrade');
  await change(page,'local-existing');await page.screenshot({path:'test-results/unified-schemes-desktop.png'});
  await page.setViewportSize({width:390,height:844});await page.waitForTimeout(350);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  assert(await page.evaluate(()=>document.querySelector('.brand').getBoundingClientRect().top>=0&&document.querySelector('.topbar').getBoundingClientRect().height===48));
  await require('./scheme-ui.cjs').openSchemes(page);await page.waitForTimeout(250);
  await page.screenshot({path:'test-results/unified-schemes-mobile.png'});
  assert.deepEqual(errors,[]);fs.writeFileSync('test-results/unified-schemes-report.json',JSON.stringify({passed:true,consoleErrors:errors,checks},null,2));console.log(checks.join('\n'));
 }catch(e){for(const p of browser.contexts().flatMap(c=>c.pages()))await p.screenshot({path:'test-results/unified-schemes-error.png'}).catch(()=>{});throw e;}
 finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
